# Generated by Django 4.2.7 on 2023-11-21 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('curator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Doctor', to='patients.doctors')),
            ],
        ),
        migrations.AddField(
            model_name='doctors',
            name='proteges',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Patients', to='patients.patients'),
        ),
    ]
