# Generated by Django 4.2.7 on 2023-11-22 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='proteges',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='curator',
        ),
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_place', models.CharField(choices=[('Office', 'Office'), ('Remote', ' Remote')], max_length=100, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration', models.DurationField(null=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.doctors')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patients')),
            ],
        ),
        migrations.AddField(
            model_name='doctors',
            name='proteges',
            field=models.ManyToManyField(related_name='Patients', to='patients.patients'),
        ),
        migrations.AddField(
            model_name='patients',
            name='curator',
            field=models.ManyToManyField(related_name='Doctor', to='patients.doctors'),
        ),
    ]
