# Generated by Django 4.2.7 on 2023-11-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_rename_doctors_doctor_rename_patients_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='proteges',
            field=models.ManyToManyField(null=True, related_name='Patients', to='patients.patient'),
        ),
    ]
