# Generated by Django 4.2.7 on 2023-12-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_doctor_city_alter_doctor_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='code',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
