# Generated by Django 4.2.7 on 2023-11-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_doctor_proteges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetings',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
