# Generated by Django 4.2.7 on 2023-12-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_alter_patient_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='proteges',
            field=models.ManyToManyField(blank=True, related_name='proteges', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='curator',
            field=models.ManyToManyField(related_name='curator', to='patients.doctor'),
        ),
    ]
