# Generated by Django 4.2.7 on 2023-11-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_meetings_progress_alter_meetings_meeting_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetings',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetings',
            name='progress',
            field=models.CharField(blank=True, choices=[('Zakończone', 'Zakończone'), ('W trakcie', 'W trakcie'), ('Nierozpoczęte', 'Nierozpoczęte')], max_length=100, null=True),
        ),
    ]
