# Generated by Django 5.0 on 2024-01-14 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_alter_doctor_group_alter_patient_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'permissions': [('doctor_permission', 'doctor_permission')]},
        ),
    ]
