# Generated by Django 4.0 on 2024-01-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetings',
            name='real_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='proteges',
            field=models.ManyToManyField(blank=True, related_name='proteges', to='patients.Patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='curator',
            field=models.ManyToManyField(related_name='curator', to='patients.Doctor'),
        ),
    ]
