# Generated by Django 4.0 on 2024-02-03 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0017_document_date_image_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='user',
            new_name='user_owner',
        ),
    ]
