# Generated by Django 4.0 on 2024-02-01 19:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0017_document_date_image_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='allowed_users',
            field=models.ManyToManyField(related_name='allowedUsersAsUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
