# Generated by Django 4.0 on 2024-02-03 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0019_document_allowed_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='user',
            new_name='user_owner',
        ),
    ]
