# Generated by Django 4.0 on 2024-02-03 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0020_rename_user_image_user_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='user_owner',
            new_name='user',
        ),
    ]
