# Generated by Django 4.0 on 2024-02-03 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0021_rename_user_owner_document_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='user_owner',
            new_name='user',
        ),
    ]
